### ISSUE TITLE
Any improvements to be made or milestones planned?

### ISSUE THREAD

**Issue by matheo** [rintoj/angular-reflux#2]
Hi
I just reached your lib and it looks awesome, thanks.

I just wonder what's the plan with it, because when you see that there are no new commits to it from 2 months ago, it sends a sad message. I saw that you are back with the angular2-virtual-scroll, do you plan to put a hand on this lib again?

Thanks for your time!

**Comment by rintoj** [comment]
@matheo thanks for your feedback. This lib is one of my favourite and we extensively used this in the recent projects. This library has been working very well for us, so I recently ported to [react](https://github.com/rintoj/react-reflux). I had a couple of learnings from this one. So I am planning to add hot module update and integration with a dev tool mostly with chrome's dev tool.

**Comment by matheo** [comment]
Thanks @rintoj 
Looking forward for improvements on this one,
I will play with it as I like your ideas using all the potential of TypeScript and modern stuff!
